repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    - id: mypy
      verbose: true
      entry: bash -c 'mypy "$@" || true' --
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.3
    hooks:
    - id: flake8

