sudo: false

language: python

python:
  - 3.7

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - pytest --cov=utils tests

after_success:
  - CI=true TRAVIS=true coveralls
